---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library('flexdashboard')
```


```{r}
library("rgdal")
library("sp")
library("raster")
library("leaflet")
library("dplyr")
```

```{r} 
### --- Read limits of Sierra Nevada Protected area
myurl <- 'https://www.dropbox.com/s/phuz9yxyiow78dt/eennpp_ed50_30.zip?dl=0'
# EPSG:23030

# Idea based on http://thebiobucket.blogspot.com.es/2013/09/batch-downloading-zipped-shapefiles.html 
wd <- getwd()
td <- tempdir()
setwd(td)

temp <- tempfile(fileext = ".zip")
download.file(myurl, temp)
unzip(temp)

shp <- dir(tempdir(), "*.shp$")

enp <- readOGR(dsn=shp, layer= sub(".shp$", "", shp), encoding="UTF-8")
unlink(dir(td))
file.remove(list.files(tempdir()))
setwd(wd)
### ---- 

### --- Read distribution of Q. pyrenaica forests
myurl <- 'https://rawgit.com/ajpelu/modis_iv/master/data_raw/geoinfo/quercus_pyrenaica_sn.zip'

# Idea based on http://thebiobucket.blogspot.com.es/2013/09/batch-downloading-zipped-shapefiles.html 
wd <- getwd()
td <- tempdir()
setwd(td)

temp <- tempfile(fileext = ".zip")
download.file(myurl, temp)
unzip(temp)

shp <- dir(tempdir(), "*.shp$")

qp <- readOGR(dsn=shp, layer= sub(".shp$", "", shp), encoding="UTF-8")
unlink(dir(td))
setwd(wd)
### ----

### Prepare Spatial data 
# Sierra Nevada limits 
enp_r <- spTransform(enp, CRS("+init=epsg:4326"))

# Select Sierra Nevada 
sn <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Espacio Natural')
sn_nat <- subset(enp_r, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Parque Nacional')

# Pyrenean forests 
qp_r <- spTransform(qp, CRS("+init=epsg:4326"))
```

Column 
-----------------------------------------------------------------------

### Chart A
```{r}
# Identificador poblaciones
popup_qp <- paste0("<strong>Population id:</strong> ", qp_r$POBLACION,
                   "<br><strong>Name:</strong> ", qp_r$LOCALIDAD,
                   "<br><strong>Valley:</strong> ", qp_r$VALLE)

# Extension capa robledales
ext_qp <- extent(qp_r)


# Map 
m <- leaflet() %>% 
  # Basemaps
  addWMSTiles('http://www.ideandalucia.es/services/toporaster10/wms?',
              layers = 'toporaster10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Topographical') %>%

  addProviderTiles("Esri.WorldImagery", group='Satellite') %>% 
  
  addWMSTiles('http://www.ideandalucia.es/wms/mdt_2005?',
              layers = 'Sombreado_10',
              options = WMSTileOptions(format = "image/png", transparent = FALSE),
              attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>',
              group = 'Hillshade') %>% 

  # Polygons 
  # addPolygons(data = sn_nat, fill=FALSE, color = 'red', weight=0.8, 
  #             group='National Park') %>% 
  addPolygons(data = sn, fill=FALSE, color = 'blue',  weight=1.5, dashArray=c(5,5),
              group = 'Natural Park') %>%
  addPolygons(data = qp_r, fillColor = 'red', fillOpacity = 0.4, stroke = FALSE,
              group= 'Q. pyrenaica forests', popup = popup_qp) %>% 
  
  # Layers control
  addLayersControl(position = 'bottomright',
                   baseGroups = c("Hillshade", "Satellite", "Topographical"),
                   overlayGroups = c('Q. pyrenaica forests','Natural Park','National Park'),
                   options = layersControlOptions(collapsed = FALSE)) 

m 

# %>% 
  # Legend
  # addLegend(position = 'bottomleft',opacity = 0.4, 
  #           colors = c('red'), 
  #           labels = c('Monterosso-Corniglia (23/09)',
  #                      'Corniglia-Vernazza (24/09)'),
  #           title = 'Hikes Italy, Cinque Terre') %>%
  #             
m

m <- leaflet() %>% addPolygons(data = qp_r, 
              group= 'Melojar (Q. pyrenaica)', 
              fillColor = 'red', fillOpacity = 0.4, stroke = FALSE,
              popup = popup_qp)




m %>% setView(lng = mean(ext_qp[1:2]), lat =mean(ext_qp[3:4]), zoom = 12) 

```

### Chart C

```{r}

```

